### ISSUE TITLE
Menu Bar- instead of Dock-Icon?

### ISSUE THREAD

**Issue by marckrenn** [ojotoxy/Brightness#2]
Thanks @ojotoxy for this super helpful deamon! Really adds some additional value to non-Apple monitors!

However, there's one tiny little aspect that's not ideal in my opinion: The permanent Dock-Icon.

Do you think you could get rid of the permanent Dock Icon in exchange for a Menu Bar icon? That would make it perfect in my eyes.

**Comment by marckrenn** [comment]
With the help of one of my colleagues, I was able to built such a version myself.
Thanks, anyway.

**Comment by marckrenn** [comment]
Here's my build, if anyone's interested.

- removed permanent Dock Icon
- re-enabled Menu Bar Icon (which has no function)
- cranked up the sync-rate to .1s

https://www.dropbox.com/sh/53i1ly4ulqmy6be/AAD6YlOZCQBYetog2UsSf9Uva?dl=0

**Comment by baragona** [comment]
If you think the changes are good can you make a pull request? Thank you very much!
