### ISSUE TITLE
Clamshell mode support

### ISSUE THREAD

**Issue by alexlouden** [ojotoxy/Brightness#7]
Hi, I just wanted to thank you for this project - it's the best app I've found for adjusting my external monitor's brightness and I've tried quite a few!

I use an external monitor with my laptop lid shut most of the time, and I was wondering whether it'd be possible to support changing the brightness like this? At the moment at night I open my laptop lid, change the internal display brightness with the keyboard buttons, and then shut the lid again 😀 

I also noticed in the console that Brightness is logging every 100ms when the lid is shut:

```
default	13:59:01.451178 +0800	Brightness	No driving display -- keeping old brightness
default	13:59:01.551195 +0800	Brightness	No driving display -- keeping old brightness
default	13:59:01.651926 +0800	Brightness	No driving display -- keeping old brightness
default	13:59:01.751925 +0800	Brightness	No driving display -- keeping old brightness
```

Thanks again!

**Comment by deepai-org** [comment]
Yes this is a good idea.

I use the physical Function keys on my external keyboard to change brightness - they don't do anything when the laptop is closed.

About the only thing I can think of is adding some custom UI to change it. But it probably can't use the same function keys...

Feel free to take a shot at solving this, any way you like, I will add it if it works :)

**Comment by baragona** [comment]
Yes this is a good idea.

I use the physical Function keys on my external keyboard to change brightness - they don't do anything when the laptop is closed.

About the only thing I can think of is adding some custom UI to change it. But it probably can't use the same function keys...

Feel free to take a shot at solving this, any way you like, I will add it if it works :)

**Comment by alexlouden** [comment]
Thanks for the quick reply! I was thinking of a simple slider - e.g.:

![image](https://user-images.githubusercontent.com/1332954/53936189-fd200a00-40e3-11e9-9ef4-364e7a244261.png)

I'm afraid I haven't done any objective C before, but if I have some free time I'll give it a shot!

**Comment by baragona** [comment]
That looks good! Thank you for helping out.

**Comment by baragona** [comment]
Can you try the latest update and see if it works for you? Has a slider now.

**Comment by alexlouden** [comment]
Hi @ojotoxy that's awesome, thank you so much! Have you thought about putting this on the mac app store? I'd definitely buy it :)

**Comment by baragona** [comment]
Can't say I have but I may look into it... Thank you.
